build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
checks:
    php: true
filter:
    paths:
        - src/*
